// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/10/2025, 1:08:04 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/home/codex/palantir_services/vue-palantir/nuxt-app/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/codex/palantir_services/vue-palantir/nuxt-app/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/codex/palantir_services/vue-palantir/nuxt-app/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/codex/palantir_services/vue-palantir/nuxt-app/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/codex/palantir_services/vue-palantir/nuxt-app/app/plugins/**/*.{js,ts,mjs}","/home/codex/palantir_services/vue-palantir/nuxt-app/app/composables/**/*.{js,ts,mjs}","/home/codex/palantir_services/vue-palantir/nuxt-app/app/utils/**/*.{js,ts,mjs}","/home/codex/palantir_services/vue-palantir/nuxt-app/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/codex/palantir_services/vue-palantir/nuxt-app/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/codex/palantir_services/vue-palantir/nuxt-app/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/codex/palantir_services/vue-palantir/nuxt-app/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;